wind_color = '#7030A0'
size31 = (8,2)
size32 = (8,3.5)
size33 = (8,5)
size34 = (8,6.5)
solar_color= '#66FF99'
wind_solar_color= '#ED7D31'
demand_color= 'blue'
deficit_color= 'indigo'
excess_color= 'darkcyan'
solar_label = 'Solar radiation (kJ/m²)'
wind_label = 'Wind speed (m/s)'
energy_label = 'Electricity (MW)'
solar_energy_label = 'Solar'
wind_energy_label = 'Wind'
demand_label = 'Demand'
demand_label2 = 'Electricity demand (MW)'
deficit_label = 'Deficit'
deficit_label2 = 'Electricity deficit (MW)'
excess_label = 'Excess'
excess_label2 = 'Electricity excess (MW)'
wind_solar_energy_label = 'Wind + Solar'
data_year = 2020
plot_folder = 'plot_images/'